"""KPI Discovery Prompts"""

from .domain_analyzer import DOMAIN_ANALYZER_SYSTEM, DOMAIN_ANALYZER_PROMPT
from .kpi_discoverer import KPI_DISCOVERER_SYSTEM, KPI_DISCOVERER_PROMPT
from .kpi_enricher import KPI_ENRICHER_SYSTEM, KPI_ENRICHER_PROMPT
from .value_ranker import VALUE_RANKER_SYSTEM, VALUE_RANKER_PROMPT

__all__ = [
    "DOMAIN_ANALYZER_SYSTEM",
    "DOMAIN_ANALYZER_PROMPT",
    "KPI_DISCOVERER_SYSTEM",
    "KPI_DISCOVERER_PROMPT",
    "KPI_ENRICHER_SYSTEM",
    "KPI_ENRICHER_PROMPT",
    "VALUE_RANKER_SYSTEM",
    "VALUE_RANKER_PROMPT",
]
