from typing import List, Optional, Literal
from pydantic import BaseModel, Field
from enum import Enum


class CategoryId(str, Enum):
    """Node category identifiers (7 categories for Solution Architecture)"""
    APPLICATIONS = "applications"
    DATA = "data"
    MESSAGING = "messaging"
    INTEGRATION = "integration"
    SECURITY = "security"
    OBSERVABILITY = "observability"
    EXTERNAL = "external"


class NodeTypeId(str, Enum):
    """All 39 node types available for Solution Architecture diagrams"""
    # Applications category (6)
    WEBAPP = "webapp"
    MOBILE = "mobile"
    BACKEND = "backend"
    API = "api"
    FUNCTION = "function"
    WORKER = "worker"
    # Data category (7)
    SQL = "sql"
    NOSQL = "nosql"
    KEYVALUE = "keyvalue"
    GRAPH = "graph"
    CACHE = "cache"
    STORAGE = "storage"
    DATALAKE = "datalake"
    # Messaging category (5)
    QUEUE = "queue"
    STREAM = "stream"
    PUBSUB = "pubsub"
    EVENTBUS = "eventbus"
    WEBHOOK = "webhook"
    # Integration category (6)
    GATEWAY = "gateway"
    MESH = "mesh"
    BFF = "bff"
    LOADBALANCER = "loadbalancer"
    CDN = "cdn"
    ETL = "etl"
    # Security category (5)
    IDP = "idp"
    AUTH = "auth"
    SECRETS = "secrets"
    WAF = "waf"
    CERTIFICATE = "certificate"
    # Observability category (5)
    LOGGING = "logging"
    METRICS = "metrics"
    TRACING = "tracing"
    ALERTING = "alerting"
    DASHBOARD = "dashboard"
    # External category (5)
    ACTOR = "actor"
    THIRDPARTY = "thirdparty"
    LEGACY = "legacy"
    PARTNER = "partner"
    CLOUD = "cloud"


class HandlePosition(str, Enum):
    """Edge connection handle positions"""
    TOP = "top"
    BOTTOM = "bottom"
    LEFT = "left"
    RIGHT = "right"


class VolumeAttachment(BaseModel):
    """Volume mount configuration for nodes"""
    name: str = Field(..., description="Volume name")
    mountPath: str = Field(..., description="Mount path in container")


class NodeData(BaseModel):
    """Data payload for a node"""
    label: str = Field(..., description="Display label for the node")
    nodeType: NodeTypeId = Field(..., description="Type of node from available categories")
    tags: Optional[List[str]] = Field(default=[], description="Optional tags for the node")
    volumes: Optional[List[VolumeAttachment]] = Field(default=[], description="Volume attachments")
    isGroup: Optional[bool] = Field(default=False, description="Whether this is a group node")


class GeneratedNode(BaseModel):
    """A node generated by the AI with logical positioning hints"""
    id: str = Field(..., description="Unique node identifier (format: node_0, node_1, etc.)")
    type: Literal["customNode", "groupNode"] = Field(
        default="customNode",
        description="Node component type"
    )
    data: NodeData = Field(..., description="Node data payload")
    logicalLayer: int = Field(
        ...,
        ge=0,
        le=10,
        description="Logical layer for positioning (0=external, 1=frontend, 2=integration, 3=services, 4=data/messaging, 5=observability)"
    )
    logicalOrder: int = Field(
        ...,
        ge=0,
        description="Order within the layer (left to right, starting at 0)"
    )
    parentGroup: Optional[str] = Field(
        default=None,
        description="Parent group ID if this node is nested inside a group"
    )


class EdgeData(BaseModel):
    """Data payload for an edge"""
    label: Optional[str] = Field(default=None, description="Optional label for the edge")
    colorFromTarget: Optional[bool] = Field(
        default=False,
        description="Use target node color instead of source"
    )


class GeneratedEdge(BaseModel):
    """A connection between two nodes"""
    id: str = Field(..., description="Unique edge identifier (format: edge_0, edge_1, etc.)")
    source: str = Field(..., description="Source node ID")
    target: str = Field(..., description="Target node ID")
    sourceHandle: Optional[HandlePosition] = Field(
        default=None,
        description="Connection point on source node"
    )
    targetHandle: Optional[HandlePosition] = Field(
        default=None,
        description="Connection point on target node"
    )
    data: Optional[EdgeData] = Field(default=None, description="Edge data payload")


class DiagramDescription(BaseModel):
    """High-level description of the generated architecture"""
    title: str = Field(..., description="Diagram title")
    summary: str = Field(..., description="Brief summary of the architecture (1-2 sentences)")
    components: List[str] = Field(..., description="List of main component names")


class GeneratedDiagram(BaseModel):
    """Complete diagram structure generated by the AI"""
    description: DiagramDescription = Field(..., description="High-level diagram description")
    nodes: List[GeneratedNode] = Field(..., description="All nodes in the diagram")
    edges: List[GeneratedEdge] = Field(..., description="All connections between nodes")


# Mapping of node types to their default logical layers for Solution Architecture
NODE_TYPE_LAYERS = {
    # Layer 0: External actors and systems
    NodeTypeId.ACTOR: 0,
    NodeTypeId.PARTNER: 0,
    NodeTypeId.THIRDPARTY: 0,
    NodeTypeId.LEGACY: 0,
    NodeTypeId.CLOUD: 0,

    # Layer 1: Frontend applications
    NodeTypeId.WEBAPP: 1,
    NodeTypeId.MOBILE: 1,
    NodeTypeId.CDN: 1,

    # Layer 2: Integration / Entry points
    NodeTypeId.GATEWAY: 2,
    NodeTypeId.BFF: 2,
    NodeTypeId.LOADBALANCER: 2,
    NodeTypeId.WAF: 2,
    NodeTypeId.MESH: 2,

    # Layer 3: Services & APIs
    NodeTypeId.API: 3,
    NodeTypeId.BACKEND: 3,
    NodeTypeId.FUNCTION: 3,
    NodeTypeId.WORKER: 3,
    NodeTypeId.AUTH: 3,
    NodeTypeId.IDP: 3,
    NodeTypeId.WEBHOOK: 3,
    NodeTypeId.ETL: 3,

    # Layer 4: Data & Messaging
    NodeTypeId.SQL: 4,
    NodeTypeId.NOSQL: 4,
    NodeTypeId.KEYVALUE: 4,
    NodeTypeId.GRAPH: 4,
    NodeTypeId.CACHE: 4,
    NodeTypeId.STORAGE: 4,
    NodeTypeId.DATALAKE: 4,
    NodeTypeId.QUEUE: 4,
    NodeTypeId.STREAM: 4,
    NodeTypeId.PUBSUB: 4,
    NodeTypeId.EVENTBUS: 4,
    NodeTypeId.SECRETS: 4,

    # Layer 5: Observability (cross-cutting)
    NodeTypeId.LOGGING: 5,
    NodeTypeId.METRICS: 5,
    NodeTypeId.TRACING: 5,
    NodeTypeId.ALERTING: 5,
    NodeTypeId.DASHBOARD: 5,
    NodeTypeId.CERTIFICATE: 5,
}
