"""
Feature Discovery Prompts

Prompts for each agent in the feature discovery pipeline.
"""

from .code_analyzer import CODE_ANALYZER_PROMPT, CODE_ANALYZER_SYSTEM
from .feature_discoverer import FEATURE_DISCOVERER_PROMPT, FEATURE_DISCOVERER_SYSTEM
from .gap_analyst import GAP_ANALYST_PROMPT, GAP_ANALYST_SYSTEM
from .tech_debt_analyst import TECH_DEBT_ANALYST_PROMPT, TECH_DEBT_ANALYST_SYSTEM
from .feature_enricher import FEATURE_ENRICHER_PROMPT, FEATURE_ENRICHER_SYSTEM
from .priority_ranker import PRIORITY_RANKER_PROMPT, PRIORITY_RANKER_SYSTEM

__all__ = [
    "CODE_ANALYZER_PROMPT",
    "CODE_ANALYZER_SYSTEM",
    "FEATURE_DISCOVERER_PROMPT",
    "FEATURE_DISCOVERER_SYSTEM",
    "GAP_ANALYST_PROMPT",
    "GAP_ANALYST_SYSTEM",
    "TECH_DEBT_ANALYST_PROMPT",
    "TECH_DEBT_ANALYST_SYSTEM",
    "FEATURE_ENRICHER_PROMPT",
    "FEATURE_ENRICHER_SYSTEM",
    "PRIORITY_RANKER_PROMPT",
    "PRIORITY_RANKER_SYSTEM",
]
